CREATE TABLE t_user (
  id                       INT(11)      NOT NULL AUTO_INCREMENT,
  user_no                  CHAR(64)     NOT NULL COMMENT '用户号',
  auto_check_no            VARCHAR(128) NOT NULL COMMENT '传给第三方的外部用户号,唯一',
  ec_code                  VARCHAR(256)          DEFAULT '' COMMENT '密码的盐',
  mobile                   CHAR(11)              DEFAULT NULL COMMENT '用户手机,用于用户登录场景',
  password                 CHAR(32)     NOT NULL COMMENT '密码',
  create_time              DATETIME              DEFAULT NULL COMMENT '用户注册时间',
  status                   INT(11)               DEFAULT '1' COMMENT '用户状态:@Enum(UserStatus:1,normal,正常;2,login_locked,登陆锁定;3,order_locked,下单锁定;4,deleted,删除)',
  lock_reason              VARCHAR(300)          DEFAULT NULL COMMENT '锁定原因',
  ab_level                 VARCHAR(20)           DEFAULT NULL COMMENT 'A/B测试资源等级',
  head_ico                 VARCHAR(256)          DEFAULT 'http://xxxxx.com/head/head_eight.png' COMMENT '头像',
  nickname                 VARCHAR(1000)         DEFAULT NULL COMMENT '用户昵称',
  sex                      INT(11)               DEFAULT '2' COMMENT '用户性别:@Enum(Sex:1,male,男;2,female,女)',
  love_state               INT(11)               DEFAULT '1' COMMENT '恋爱状态:@Enum(UserLoveState:1,single,单身狗;2,non_single,已脱单)',
  favorite_snacks          VARCHAR(32)           DEFAULT '' COMMENT '最喜欢吃的零食',
  plusv_certification_info VARCHAR(20)           DEFAULT NULL COMMENT '用户加V认证信息描述',
  email                    VARCHAR(50)           DEFAULT NULL COMMENT 'Email,用于用户登录',
  area_id                  INT(11)               DEFAULT NULL COMMENT '学校ID',
  recommend_user_id        INT(11)               DEFAULT NULL COMMENT '推荐人id',
  recommend_balance        DECIMAL(15, 3)        DEFAULT '0.000' COMMENT '推荐返现总额',
  account_id               INT(11)               DEFAULT NULL COMMENT '账户id',
  upgrade_flag             INT(11)      NOT NULL DEFAULT '0' COMMENT '@Boolean:是否切加密新算法标志',
  last_login_time          DATETIME              DEFAULT NULL COMMENT '上次登陆时间(最后一次登陆时间)',
  PRIMARY KEY (id),
  UNIQUE KEY un_user_no (user_no),
  UNIQUE KEY uni_mobile (mobile),
  KEY email (email),
  KEY ind_create_time (create_time),
  KEY ind_account_id (account_id),
  KEY ind_nickname (nickname(10)),
  KEY last_login_time (last_login_time) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8;
